"""
    Filename: run_brainstorm_demo.py
    Author: Austin Pursley
    Created: 3/24/2018
    Edited: 3/24/2019
    Python Version 2.7
"""

from brainstorm import brainstorm

# list of various STEM subjects/ideas to brainstorm with
stem_soup = [
    'DMD',
    'machine learning',
    'image processing',
    'LED',
    'haptic motor',
    'microcontroller',
    'microscope',
    'fruit fly',
    'DNA sequencer',
    'divide and conquer',
    'insect antenna',
    'armadillo armour',
    'e-nose',
    'wireless',
    'fiber optic',
    'simulation',
    'aquarium',
    'zebra fish',
    'genetic engineering',
    'fly eye',
    'plant',
    'optimization',
    'optogenetics',
    'lab rats',
    'reddit',
    'twitter',
    'twtich',
    'facebook',
    'amazon',
    'sonar',
    'radar',
    'lidar',
    'thermal camera',
    'VL camera',
    'sensor-fusion',
    'array/matrix',
    'neural network',
    'classificaiton',
    'regression',
    'genetic algorithm',
    'video game',
    'plastic',
    'gravity',
    'accelerometer',
    '3D printing',
    'FFT',
    'thermometer',
    'sound speaker',
    'microphone',
    'photocell',
    'electronic water valve',
    'force sensor pad',
    'RGB-D camera',
    'vibration sensor switch',
    'piezo element',
    'light sensor',
    'flex sensor',
    'GPS',
    'network',
    'UV',
    'photolithography',
    'pressure sensor',
    'underwater',
    'magnet',
    'wind speed sensor',
    'gyroscope',
    'oscilloscope',
    'fingerprint sensor',
    'radio controlled',
    'ultrasonic rangefinder',
    'Wii controller',
    'Foot pedal',
    'barcode',
    'microrganisms',
    'satelight',
    'rocket',
    'sunshine',
    'solar',
    'infragram',
    'radiation',
    'motor',
    'quadcopter',
    'eulerian video magnification',
    'ants',
    'Juypter notebook',
    'emergence',
    'biomimicry',
    'sensory substituion',
    'microfluids',
    'strategy game',
    'enzyme',
    'protein',
    'robot arm',
    'pharmacy',
    'warehouse',
    'mobile app',
    'bicycle',
    'car',
    'train',
    'truck',
    'smart watch',
    'smart phone',
    'rain',
    'hurricane',
    'tornado',
    'lightning',
    'music',
	'magnetoreception',
	'cryptochrome',
	'space junk',
	'harpoon',
	'laser',
	'ECG',
    'voice warning'
]

brainstorm(subject_list=stem_soup, minutes=2)